config/docs.ts, content/docs/components/word-rotate.mdx, registry/components/example/word-rotate-demo.tsx, registry/components/magicui/word-rotate.tsx, registry/index.tsx
Here's an example PR of how to contribute to Magic UI!
There are only 5 files you need to change to add a new component :) 
I would love if you could also post a demo video of what you made so we can review it and give feedback easily
https://github.com/magicuidesign/magicui/assets/16860528/45b703b5-36df-4f82-82d1-3971779730e2
=> feat: add word rotate component

.gitignore, config/docs.ts, content/docs/components/typing-animation.mdx, registry/components/example/typing-animation-demo.tsx, registry/components/magicui/typing-animation.tsx, registry/index.tsx
[Typing animation component](https://github.com/magicuidesign/magicui/issues/16)
https://github.com/magicuidesign/magicui/assets/29210732/8bc5123d-4a08-4776-aa9b-0eae1d523929
=> feat: add typing animation component

registry/components/magicui/magic-card.tsx
Remove duplicate cn function declaration
=> Use cn from lib

config/docs.ts, content/docs/components/wavy-text.mdx, registry/components/example/wavy-text-demo.tsx, registry/components/magicui/wavy-text.tsx, registry/index.tsx
[text animation] wavy text #23
=> feat: add wavy text component

config/docs.ts, content/docs/components/blur-in.mdx, content/docs/components/wavy-text.mdx, registry/components/example/blur-in-demo.tsx, registry/components/magicui/blur-in.tsx, registry/index.tsx
[text animation] text blur in https://github.com/magicuidesign/magicui/issues/23
https://github.com/magicuidesign/magicui/assets/68553016/39a78d97-451c-4ad7-8c97-d73818b8dfea
=> feat: add blur in text component (#18)

config/docs.ts, content/docs/components/separate-away.mdx, registry/components/example/separate-away-demo.tsx, registry/components/magicui/separate-away.tsx, registry/index.tsx
[[text animation] separate away #21](https://github.com/magicuidesign/magicui/issues/21)
https://github.com/magicuidesign/magicui/assets/64883022/6efba075-0607-4502-8858-491c21837ee7
=> feat: separate away

config/docs.ts, content/docs/components/scroll-based-velocity.mdx, package.json, pnpm-lock.yaml, registry/components/example/scroll-based-velocity-demo.tsx, registry/components/magicui/scroll-based-velocity.tsx, registry/index.tsx
[[text animation] Scroll Based Velocity Text #13](https://github.com/magicuidesign/magicui/issues/13)
I altered the code so that it now dynamically created the correct number of children to fill its container without overflowing (basically dynamic sizing/repetitions).
https://github.com/magicuidesign/magicui/assets/64883022/e97d2e75-6f0b-4011-8efb-11b0848b6db7
=> feat: scroll based velocity text

config/docs.ts, content/docs/components/avatar-circles.mdx, registry/components/example/avatar-circles-demo.tsx, registry/components/example/word-rotate-demo.tsx, registry/components/magicui/avatar-circles.tsx, registry/index.tsx
Feature: 
Overlapping circles of avatars.
Also, fixed typo in **registry/components/example/word-rotate-demo.tsx**
Changed TextRevealDemo() to WordRotatelDemo()
=> feat: avatar-circles

config/docs.ts, content/docs/components/word-pull-up.mdx, registry/components/example/word-pull-up-demo.tsx, registry/components/magicui/word-pull-up.tsx, registry/index.tsx
Feature: Word Pull Up Text Animation
Pulled from issues: https://github.com/magicuidesign/magicui/issues/15
=> Add Word Pull Up component

config/docs.ts, content/docs/components/icon-cloud.mdx, package.json, pnpm-lock.yaml, registry/components/example/icon-cloud-demo.tsx, registry/components/magicui/icon-cloud.tsx, registry/index.tsx
Feat: interactive Icon Cloud
fixes #27
https://github.com/magicuidesign/magicui/assets/96728449/d9dbf4e2-c155-419a-bb7d-7be8b951fb62
=> feat:Interactive-Icon-Cloud

config/docs.ts, content/docs/components/gradual-spacing.mdx, registry/components/example/gradual-spacing-demo.tsx, registry/components/magicui/gradual-spacing.tsx, registry/index.tsx
As mentioned in  #12 , this PR is genereated as per accordance.
Component was taken from https://variantvault.chrisabdo.dev/text-variants as mentioned in the issue #22  .
Any discussion or doubts are entertained below.
=> feat: gradual-spacing added

registry/components/example/letter-pullup-demo.tsx, registry/components/magicui/letter-pullup.tsx
This PR fix the issue: #51 
Before:
After:
=> fix: text visible in dark mode in Letter PullUp component

config/docs.ts, content/docs/components/word-fade-in.mdx, registry/components/example/word-fade-in-demo.tsx, registry/components/magicui/word-fade-in.tsx, registry/components/magicui/word-pull-up.tsx, registry/index.tsx
- Feature : Add word fade in component
- Referring Issue : https://github.com/magicuidesign/magicui/issues/14
https://github.com/magicuidesign/magicui/assets/92677078/ee14af66-a27c-4be9-9c33-e62ebcfc0f1a
=> feat: add word fade in component

config/docs.ts, content/docs/components/fade-text.mdx, registry/components/example/fade-text-demo.tsx, registry/components/magicui/fade-text.tsx, registry/index.tsx
[Fade Text component](https://github.com/magicuidesign/magicui/issues/20)
https://github.com/magicuidesign/magicui/assets/29210732/b643b89a-fc0f-4b1b-a88a-647d1c782567
=> add: fade text component

config/docs.ts, content/docs/components/shiny-button.mdx, registry/components/example/shiny-button-demo.tsx, registry/components/magicui/shiny-button.tsx, registry/index.tsx
This PR introduces a new shiny button component featuring dynamic styles that adapt to both dark and light modes. The button's design ensures consistent aesthetic appeal across different themes, enhancing the user interface's visual experience.
Preview:
You can see the shiny button in action in this video demonstration:
https://github.com/magicuidesign/magicui/assets/101147375/31e62c13-95ac-4307-bcf4-fb11ab0854ee
=> feat: Add Shiny Button Component

config/docs.ts, content/docs/components/box-reveal.mdx, registry/components/example/box-reveal-demo.tsx, registry/components/magicui/box-reveal.tsx, registry/index.tsx
Feature: Sliding box animation that reveals text behind it.
**2nd cleaned branch.**
Checked out from main. Followed instructions here: https://github.com/magicuidesign/magicui/pull/34#issuecomment-2128393230
https://github.com/magicuidesign/magicui/assets/20110627/2fe00fe0-310a-49ec-83e0-f37766cb8f8b
=> feat: box-reveal

config/docs.ts, content/docs/components/neon-gradient-card.mdx, registry/components/example/neon-gradient-card-demo.tsx, registry/components/magicui/neon-gradient-card.tsx, registry/index.tsx, tailwind.config.ts
This pull request adds a new **NeonGradientCard** component to the library. This component displays a card with an animated neon gradient effect using Tailwind CSS and React.
- **Neon Gradient Effect**: Uses a linear gradient to create a dynamic neon effect on the ::before and ::after pseudo-elements.
- **Animation**: Pseudo-elements animate their background position to create a moving gradient effect.
- **Dynamic Dimensions**: Automatically calculates the container's width and height, adjusting the styles of the pseudo-elements accordingly, without user input.
- **Customization**: Allows customization of gradient colors, border size, and border radius via props.
1. className (string): Additional CSS classes for the main container.
2. children (ReactNode): Content to display inside the …
=> feat: neon gradient card component

components/component-preview.tsx
fixes #82 
Added reload button to view the animation again without having to reload the page every time.
https://github.com/magicuidesign/magicui/assets/96728449/c1fad928-e592-44a0-8c09-f75841d9adf6
=> feat:Added reload button to view animation again

content/docs/components/icon-cloud.mdx
=> docs:note-for-icon-cloud-that-could-cause-some-issues-with-the-component

config/docs.ts, content/docs/components/gauge-circle.mdx, registry/components/example/gauge-circle-demo.tsx, registry/components/magicui/gauge-circle.tsx, registry/index.tsx
Hello
This PR adds the GaugeCircle component, which is used to display a circular gauge with a percentage value.
[Gauge Circle _ Magic UI y 1 página más - Personal_ Microsoft_ Edge Beta 2024-05-28 14-44-00.webm](https://github.com/magicuidesign/magicui/assets/101147375/4f423e93-e458-47a6-99f6-7825d8425583)
=> feat: Add Gauge Circle component and documentation

config/docs.ts, content/docs/components/confetti.mdx, package.json, registry/components/example/confetti-basic-cannon.tsx, registry/components/example/confetti-custom-shapes.tsx, registry/components/example/confetti-emoji.tsx, registry/components/example/confetti-fireworks.tsx, registry/components/example/confetti-random-direction.tsx, registry/components/example/confetti-side-cannons.tsx, registry/components/example/confetti-stars.tsx, registry/components/magicui/confetti.tsx, registry/index.tsx
- **Dynamic Confetti Effect**: Generates animated confetti with customizable properties.
- **Customization**: Allows extensive customization of the confetti properties, including colors, shapes, and physics parameters.
- **Performance**: Built on [canvas-confetti](https://www.npmjs.com/package/canvas-confetti) Utilizes web workers for better performance.
1. **Confetti**: Generates confetti with customizable properties.
2. **Confetti.shapeFromPath**: Generates confetti with custom shapes from a given SVG path.
3. **Confetti.shapeFromText**: Generates confetti with custom shapes from a given text.
1. **particleCount** (number): The number of confetti particles to launch
2. **angle** (number): The angle in degrees at which to launch confetti
3. **spread** (number): The spread in degrees of …
=> [Feat] New Component: Confetti Effect

CONTRIBUTING.md
Add more info on the 5 files to change when contributing
=> [Docs] Update contributing guide

config/docs.ts, content/docs/components/animated-subscribe-button.mdx, registry/components/example/animated-subscribe-button-demo.tsx, registry/components/magicui/animated-subscribe-button.tsx, registry/index.tsx
* Fix Issue #92
Animated Subscribe button added with custom props and well curated info page
=> [Feat] Animated Subscribe Button

config/docs.ts, content/docs/components/sparkles-text.mdx, registry/components/example/sparkles-text-demo.tsx, registry/components/magicui/sparkles-text.tsx, registry/index.tsx
This pull request adds a new **Sparkles Text** component to the library. This component displays a text with animated sparkles effect.
- **Dynamic Sparkles Effect** : Generates animated sparkles that appear around the text.
- **Animation** : Sparkles are animated using Framer Motion for smooth transitions and movements.
- **Customization**: Allows customization of the number of sparkles, their colors, and additional CSS classes via props.
1. as (ReactElement): The component to be rendered as the text (default: <div />).
2. className (string): Additional CSS classes for the main container (default: "").
3. text (string): The text to be displayed (required).
4. sparklesCount (number): The count of sparkles (default: 10).
5. colors (object):
5.1. first (string): First color of the sparkles …
=> [Feat] sparkles-gradient-text component

config/docs.ts, content/docs/components/cool-mode.mdx, registry/components/example/cool-mode-custom.tsx, registry/components/example/cool-mode-demo.tsx, registry/components/magicui/cool-mode.tsx, registry/index.tsx
- **Dynamic Particle Effect**: Generates animated particles with customizable properties.
- **Customization**: Allows extensive customization of the particle properties, including shapes, sizes, and physics parameters.
- **Performance**: Efficiently handles animations to ensure smooth performance.
1. **particle** (string): The particle shape ("circle") or URL of the custom image.
2. **size** (number): Size of the particle.
3. **particleCount** (number): The number of particles to generate.
4. **speedHorz** (number): Horizontal speed of the particles.
5. **speedUp** (number): Upward speed of the particles.
- "circle"
- Custom URL/PATH
https://github.com/magicuidesign/magicui/assets/106103625/5430bd76-d151-44e9-b1e7-4144738dba54
=> [Feat] New Component: Cool Mode Effect

components/toc.tsx
This pull request refactors the TableOfContents component to improve rendering efficiency. It also includes a refinement to the DashboardTableOfContents component to include links in steps. These changes optimize the performance of the code and enhance the user experience.
adresses: https://github.com/magicuidesign/magicui/issues/96
=> Refactor TableOfContents component and improve rendering efficiency

components/landing/hero-client.tsx, components/landing/testimonials.tsx, components/main-nav.tsx, components/mode-toggle.tsx, components/site-banner.tsx, components/ui/badge.tsx, registry/components/example/dock-demo.tsx, styles/globals.css
Added things ---
1. Inter-font variation change
2. hero section layout change
3. open-source badge added
4. only dark and light mode toggle
5. No layout shift
Thanks,
Arghya
=> Magic UI Redesign stages

config/docs.ts, content/docs/components/particles.mdx
=> feat: add particles

components/landing/hero-client.tsx, components/mode-toggle.tsx
- Fix the position of the OSS badge in the Hero section on mobile screens
- Fix the dark/light mode toggle button
=> Homepage Hero Section bug fix

README.md
Fix link to correct contributors graph
=> [Bug Fix] Fix correct contributors link

registry/components/example/avatar-circles-demo.tsx, registry/components/magicui/avatar-circles.tsx
This PR refactors the [AvatarCircles ](https://magicui.design/docs/components/avatar-circles)component to enhance its flexibility and maintainability by allowing dynamic avatar URLs to be passed as props. 
This change makes the component more reusable and simplifies the code.
-[x] Simplified the JSX structure, making it easier to read and maintain.
Updated the usage of the AvatarCircles component to pass the avatar URLs as props:
```tsx copy
import AvatarCircles from "@/components/AvatarCircles";
const avatarUrls = [
"https://avatars.githubusercontent.com/u/16860528",
"https://avatars.githubusercontent.com/u/29210732",
"https://avatars.githubusercontent.com/u/20110627",
];
function App() {
return (
<AvatarCircles 
numPeople={5} 
className="custom-class" 
avatarUrls={avatarUrls} 
/>
);
} …
```
=> refactor: pass the avatars urls as props for component reusability

content/docs/installation/react.mdx
Fixing the typo as mentioned here: https://github.com/magicuidesign/magicui/issues/165
=> fix: remove dev dependency typo

content/docs/installation/svelte.mdx
fixes ClassName type import https://github.com/magicuidesign/magicui/issues/131#issuecomment-2172145137
=> refactor: update clsx import in svelte installation documentation

registry/components/magicui/particles.tsx
Added a condition to check if the hex string length is 3.
=> fix: hex to rgb in particles component

registry/components/magicui/magic-card.tsx
Improve the performance of the `MagicCard` component by optimizing mouse event handling and gradient effect updates.
- **Optimized Mouse Event Handling**: Added `useCallback` to memoize `handleMouseMove` and `handleMouseLeave` functions, reducing unnecessary re-renders.
- **Improved Gradient Management**: Added `handleMouseLeave` to reset the gradient effect when the mouse leaves the component.
- **Smoother Performance**: Reduced re-renders and optimized gradient updates.
- **Resource Efficiency**: Improved handling of mouse events and gradient rendering.
```jsx
import { MagicCard } from './components/MagicCard';
export default function Example() {
return (
<MagicCard
gradientSize={200}
gradientColor="#ff5722"
gradientOpacity={0.8}
className="example-card"
>
<h1>Hello, MagicCard!</h1> …
```
=>  perf(registry): improve MagicCard performance with useCallback and extend interface for enhanced flexibility 

registry/components/magicui/ripple.tsx
Title:
Fix: Ripple animation issue #213
Description:
This PR addresses issue #213 by fixing the initial ripple animation positioning issue. The ripples now correctly appear centered upon page refresh without briefly showing in the bottom right corner.
Changes:
Corrected the initial positioning logic for the ripple animation.
Ensured that the animation starts correctly without visual glitches.
Testing:
Reproduced the issue on the local setup.
Applied the fix and verified that the ripples appear centered on page refresh.
Tested the animation in multiple browsers to ensure consistency.
Issue Reference:
Fixes #213
Additional Information:
No additional dependencies were added.
This fix is backward compatible with existing functionality.
=> fix: fixed the initial ripple comes on the right bottom

registry/components/magicui/number-ticker.tsx
fixed type error in number ticker component
=> fix: #140 fixed number ticker issue

config/docs.ts, content/docs/components/hyper-text.mdx, registry/components/example/hyper-text-demo.tsx, registry/components/magicui/hyper-text.tsx, registry/index.tsx
Adding hyper text animation.
https://github.com/user-attachments/assets/d6f2627e-cadc-4994-812b-0bc1b6521957
=> feat: add hyper text component

content/docs/components/tweet-card.mdx
=> fix(156): change type id to string

content/docs/components/blur-fade.mdx, registry/components/magicui/blur-fade.tsx
fix: #260
framer-motion update the `margin` is type 
about link: https://github.com/framer/motion/pull/2445/files
=> fix(blur-fade): `margin` type

config/docs.ts, content/docs/components/flickering-grid.mdx, registry/components/example/flickering-grid-demo.tsx, registry/components/magicui/flickering-grid.tsx, registry/index.tsx
Added the flickering grid component with docs
=> feat: add flickering grid component

config/docs.ts, content/docs/components/hero-video-dialog.mdx, registry/components/example/hero-video-dialog-demo-top-in-bottom-out.tsx, registry/components/example/hero-video-dialog-demo.tsx, registry/components/magicui/hero-video-dialog.tsx, registry/index.tsx
Added a hero video dialog component with 8 different animation effects.
=> feat: add hero video dialog component

content/docs/installation/nextjs.mdx
this has been bugging me since yesterday night
=> fix: incorrect labelling of component

registry/components/magicui/blur-in.tsx
className is now working in imported component
=> ClassName was not working with blurin component

components/component-preview.tsx, components/main-nav.tsx, components/tech-stack.tsx, config/docs.ts, registry/components/example/dock-demo.tsx
This pull request aims to improve the accessibility performance of our Magic UI design by addressing color contrast issues and adding ARIA labels. The changes made in this PR have increased the accessibility score from 84 to 93.
- Added ARIA labels to improve screen reader accessibility and navigation.
- Improved readability and usability for users with visual impairments
- Enhanced accessibility performance, increasing the score from 84 to 93
- Better compliance with Web Content Accessibility Guidelines (WCAG)
Please review the changes and provide feedback on the updated design. Thank you for your attention to accessibility!
Let me know if you'd like me to make any changes!
=>  Improved Accessibility for Magic UI Design

config/docs.ts
https://github.com/magicuidesign/magicui/issues/344
=> fix(docs): fix React.js Page not found error

registry/default/magicui/flickering-grid.tsx
- **fix flickering grid resize**
- **fix(flickeringGrid): formatting of FlickerinGrid**
=> flickering grid resize

registry/default/magicui/magic-card.tsx
This pull request refactors the MagicCard component to enhance its mouse event handling, making it more robust and efficient. Key changes include:
Replaced inline event listeners with listeners attached to the document.
Transitioned from React events to native MouseEvent for better control.
Added cardRef for referencing the card element in event handlers.
Modified mousemove, mouseout, and mouseenter event handling logic.
Refactored handleMouseMove, handleMouseOut, and handleMouseEnter to use native MouseEvent.
Implemented cardRef to get card element dimensions for precise event handling.
Ensured cleanup of event listeners in the useEffect hook for better performance.
https://github.com/user-attachments/assets/9084d477-4ab8-4661-a1d1-256519444c43 …
=> Refactor MagicCard component for improved mouse event handling

registry/default/example/avatar-circles-demo.tsx, registry/default/magicui/avatar-circles.tsx
fix #305 
Separate PRs from #326
=> updated: avatarcircles component to support profie urls

components/ui/button.tsx, registry/default/magicui/rainbow-button.tsx
=> fix: update rainbow button line bug

components/mobile-nav.tsx, components/ui/button.tsx, registry/default/magicui/hyper-text.tsx, registry/default/magicui/rainbow-button.tsx
Fix issue #331 
https://github.com/user-attachments/assets/3de8021b-cb27-4ca7-b2d5-984e211b9553
=> Fix #331: Add SheetClose and update usage to close mobile menu

registry/default/magicui/confetti.tsx
- added `displayName` for the component
- awaited all the `promises`
=> fix: awaited all the promises and added displayname

registry/default/example/file-tree-demo.tsx, registry/default/magicui/file-tree.tsx
=> fix: add filetree accessibility fix

content/docs/components/hyper-text.mdx, registry/default/example/hyper-text-demo.tsx, registry/default/magicui/hyper-text.tsx, registry/registry-ui.ts
fixed https://github.com/magicuidesign/magicui/issues/424 and more fixes
=> fix: update hyper text component

registry/default/example/dock-demo.tsx, registry/default/magicui/dock.tsx
=> fix: update dock props

lib/rehype-npm-command.ts
fix #356
- Add npm create start with in rehype-npm command.ts
=> feat: add npmCopyButton functionality in vite astro and remix

registry/default/magicui/bento-grid.tsx
This pull request aims to enhance code maintainability and readability, by **extracting the types for component props** into separate type definitions. 
This refactor ensures a cleaner separation of concerns, making it easier to manage and update prop types across the codebase.
=> refactor: extract types for component props in independent definitions

registry/default/example/particles-demo.tsx, registry/default/magicui/particles.tsx
So, the issue is that when you resize the browser window, the particles refresh and create a flickering effect. This PR fixes that.
=> fix: fixing the flickering particles issue on resize

registry/default/example/particles-demo.tsx
=> fix: remove q in particles

components/mdx-components.tsx
Changed the full look of `mdx-props-table`
=> feat: changed the mdx table style

styles/globals.css
=> feat: smooth css scroll

__registry__/index.tsx, config/docs.ts, content/docs/components/line-shadow-text.mdx, public/r/index.json, public/r/styles/default/line-shadow-text.json, registry/default/example/line-shadow-text-demo.tsx, registry/default/magicui/line-shadow-text.tsx, registry/registry-examples.ts, registry/registry-ui.ts, tailwind.config.cjs
=> feat: line shadow text component added

content/docs/components/aurora-text.mdx, public/r/index.json, public/r/styles/default/aurora-text.json, registry/registry-ui.ts
Adding the correct colors through CSS Variable.
=> fix: aurora text css variable

registry/magicui/particles.tsx
This line generated a typescript error on my end, this fixes it
=> Add default value to resizeTimeout in particles.tsx

app/(docs)/docs/[[...slug]]/page.tsx
Fixed the sticky behaviour of TableofContent in every page
=> sticky behaviour of TableOfContent 

registry/example/pointer-demo-1.tsx
=> fix: pointer demo card style fixed

content/docs/components/interactive-grid-pattern.mdx, content/docs/components/line-shadow-text.mdx
Swaps the 'Default' and 'Description' columns in the props tables for improved readability and consistency across documentation pages.
=> Standardizes certain components prop sections

registry/magicui/ripple.tsx
=> removing hsl() from the ripple

registry/example/text-animate-demo.tsx, registry/magicui/text-animate.tsx
memoized the component at export level to avoid re-rendering on any state change from parent component
=> feat: memoize the component to avoid re-rendering

lib/rehype-component.ts
=> replace @/registry with @/components

content/docs/components/border-beam.mdx, registry/example/border-beam-demo-2.tsx, registry/magicui/border-beam.tsx
https://github.com/user-attachments/assets/9cfe906e-8af1-42fe-b6a2-c57c76369b3e
=> feat: Add 'borderWidth' prop to Border Beam 
