components/landing/hero-client.tsx
Fix Chevron Display on Button
Issue:
The chevron was not appearing on the button "Browse components"
Solution:
I have fixed the issue by adjusting the tailwind classes on the button.
Details of Changes:
On "hero-client" component at line "136" i deleted the overflow-hidden
Screenshots:
=> :bug: [FIX] - fixed the bug that prevented the chevron from being display

components/site-header.tsx, registry/components/magicui/number-ticker.tsx
- Fix: Dark mode github star button number
- Feat: Use cn in number ticker class
Before:
After:
=> fix: dark mode github star button number & use cn in number ticker class

registry/components/magicui/dot-pattern.tsx
> https://magicui.design/docs/components/dot-pattern
`cx={cy}` to `cx={cx}`
error: 'cx' is assigned a value but never used
=> fix: cx set as cy in dot-pattern component

registry/components/example/tweet-card-demo.tsx, registry/components/example/tweet-card-images.tsx, registry/components/example/tweet-card-meta-preview.tsx, registry/components/magicui/dot-pattern.tsx
ref. #103 
It seems like TweetCard isn't rendering due to server-side rendering.
I've switched it to ClientTweetCard so it can run on the client side instead, and left an explanation. To avoid confusion.
=> feat: change the demo component in the TweeCard document

registry/components/magicui/fade-text.tsx
Replace the h1 by the span, to respect the semantic/seo and that the user can use the text anywhere.
You only have to wrap the component with the desired tag:
```tsx
<h1>
<FadeText
className=“text-4xl font-bold text-black dark:text-white”
direction=“right”
framerProps={{
show: { transition: { delay: 0.4 } },
}}
text=“Fade Right”
/>
</h1>
```
Translated with DeepL.com (free version)
=> Replace <h1> with <span>.

registry/components/example/animated-shiny-text-demo.tsx
The example demonstrates using a component called "TextShimmer," which is imported from "@/components/magicui/animated-shiny-text". However, the file animated-shiny-text does not contain a TextShimmer export; it only exports AnimatedShinyText.
This fix makes use of the correct import in the demo.
OLD:
NEW:
=> [BUG FIX] Wrong import being used in example

middleware.ts
Adds the `middleware.ts` file to deploy `https://magicui.engyne.page/` as `/blog`
How to test:
- Install & Run the project
- Navigate to http://localhost:3000/blog, you should a list of blog posts
- Navigate to http://localhost:3000/blog/tailwind-font-size, you should see a blog post about Tailwind Font Size
Before deploy, make sure that all other routes are still reachable.
=> Feature: Add Engyne as /blog

content/docs/components/gauge-circle.mdx
Addresses: https://github.com/magicuidesign/magicui/issues/133
Changes Made:
- Added guage-circle.tsx file path to docs.
=> fix: gauge-circle-docs

content/docs/components/animated-subscribe-button.mdx, registry/components/example/animated-subscribe-button-demo.tsx, registry/components/magicui/animated-subscribe-button.tsx
Addresses issue: https://github.com/magicuidesign/magicui/issues/135
Changes Made:
- Updated **AnimatedSubscribeButton** color to black/white
- Renamed prop **brand** to **buttonColor** for clarity and replaced references.
- Updated docs.
=> fix: animate-subscribe-button-color

registry/components/magicui/border-beam.tsx
Issue:
When placing the border beam component around a card, the contents inside it become unclickable. I encountered this issue recently when trying to use the component along with a pricing component. For images, this is not a big deal, but for any buttons/links/texts this should be fixed.
My suggestion is adding the `pointer-events-none` tailwind class, which resolves the issue.
Changes made:
- Updated `registry/components/magicui/border-beam.tsx` component by adding the tailwind class to the div
=> fix: improve accessibility of border beam component

registry/components/magicui/number-ticker.tsx
Hi @dillionverma,
While reviewing Issue #160 reported by @alamenai, I noticed that the last two digits in the Number Ticker component were attached together, and there was no space between them.
@itsarghyadas commented a few days ago suspecting that the issue might be caused by the `tabular-nums` className. To address this, I have applied the `tracking-wider` class from Tailwind CSS to the component, which resolved the spacing issue.
Here is the updated code snippet with the `tracking-wider` class added:
```typescript
return (
<span
className={cn(
'inline-block tabular-nums text-black dark:text-white tracking-wider',
className,
)}
ref={ref}
/>
)
```
- @dillionverma
- @itsarghyadas
- Confirm that the number ticker now displays digits with appropriate spacing.
- Verify that the addition of …
=> Fix Number Ticker Component Spacing Issue (#160)

registry/components/magicui/ripple.tsx
Fixed an issue with Vercel deployments and TS warnings in Ripple component as per this issue: https://github.com/magicuidesign/magicui/issues/168
=> fix: ripple component display name

.eslintrc.json, .husky/pre-push, .prettierrc, components/analytics.tsx, package.json, pnpm-lock.yaml
@dillionverma
fix the previous PR by creating small commits and setting the linting for other branches exclude main branch just for testing
=> fix : enforce linting / formatting standards (#80) 

registry/components/magicui/typing-animation.tsx
Changed the `<TypingAnimation />` component logic to avoid duplicated characters by updating it to use `text.substring(..)` instead of concatenating with `prevState + text.charAt(i)`.
Using small durations, e.g., `<TypingAnimation duration={5} />`, can duplicate characters. This does not always happen, but when switching tabs or when the application is in the background, it is more prone to happen.
=> fix: prevent duplicated characters in typing animation.

content/docs/cli.mdx
Documentation for the magicui-cli on the Magic UI website
=> Add CLI documentation

registry/components/magicui/animated-list.tsx
This pull request aims to enhance code maintainability and readability, by **extracting the types for component props** into separate type definitions. 
This refactor ensures a cleaner separation of concerns, making it easier to manage and update prop types across the codebase.
=> refactor: create independent types definitions for the component's props

package.json
`husky install` is deprecated in husky@v9.
[https://github.com/typicode/husky/releases/tag/v9.0.1](https://github.com/typicode/husky/releases/tag/v9.0.1)
fix:
=> fix: `husky install` command is deprecated in husky@v9

content/docs/components/text-reveal.mdx
`text-reveal` component doesn't have children
=> docs(text-reveal): remote prop `children`

components/sidebar-nav.tsx
- adding the following active animation on the sidebar nav menu items 
- removing the underline from the disabled items
=> feat: adding following active animaton on the sidebar nav menu items

content/docs/components/number-ticker.mdx, registry/components/example/number-ticker-decimal-demo.tsx, registry/components/magicui/number-ticker.tsx, registry/index.tsx
Update number-ticker component by allowing it to accept and display decimal places. This feature will provide more flexibility in presenting non-integer numbers within the ticker component.
- Updated the number-ticker to handle decimal places input by adding `decimalPlaces` props.
- Added `number-ticker-decimal-demo` basic showcase.
- Update `number-ticker.mdx` docs.
[magicui-number-ticker-decimal.webm](https://github.com/user-attachments/assets/260d50f1-d2d4-4757-8808-000c091892c0)
=> feat: add number-ticker to accept decimal places

registry/default/magicui/dock.tsx
Added the fix for the `mouseX` error on the dock component.
Needed to fix the `renderChildren` function to get rid of that error.
=> fix: fixed the dock component mouseX error

registry/default/magicui/particles.tsx
Added pointer-events-none class to the main container div in the Particles component
This fixes the issue with carousel button interactions
The Particles component was unintentionally blocking mouse events on elements beneath it, particularly affecting carousel buttons. This simple fix allows click events to pass through to the underlying elements.
=> fix: add pointer-events-none class to particles container

registry/default/magicui/shine-border.tsx
Make sure the elements inside can be interacted with, rather than having borders blocking events
Here is a preview video:
https://github.com/user-attachments/assets/713cddc1-3def-4531-a549-d5e93d28585e
=> Fix: add shine border pointer events none

registry/default/magicui/particles.tsx
Without cancelling animation frame, you'll end up with orphaned animation frame loops running in the background when the component rerenders.
=> Memory leak (orphaned raf loop) fix: Cancelling animation frame in particles.tsx on rerender

registry/default/magicui/shiny-button.tsx
Currently you cannot use the property `onClick` for `ShinyButton`. Since the rest of the props (`...props`) are passed to `motion.button`, I extended `ShinyButtonProps` with `HTMLMotionProps<"button">`.
=> Add motion button props to shiny button

registry/default/magicui/flip-text.tsx
This PR corrects the default export name in the file `flip-text.tsx`, renaming `export default SlightFlip` to `export default FlipText`. This change ensures consistency across the project.
Note that the name `SlightFlip` does not appear in any other files in the project.
=> fix: rename SlightFlip to FlipText for consistency

content/docs/components/animated-shiny-text.mdx
This PR resolves issue #362, where the custom animation for the `AnimatedShinyText` component was not working due to a misspelled variable in the `tailwind.config.js` file in documentation.
Changes:
- Renamed the CSS variable `--shimmer-width` to `--shiny-width` in the `tailwind.config.js` to match the variable used in the `AnimatedShinyText` component.
Testing:
- Verified that the animation now works as expected after updating the variable.
- Ensured that the manual installation guide reflects the correct configuration.
Fixes #362
=> Fix: Correct misspelled variable in Tailwind config for AnimatedShinyText component (#362)

README.md
Changes Made:
- Added Discord invite link to README
- Got rid of rate limited by upstream service message.
=> docs: added-discord-invite-link

registry/default/magicui/animated-list.tsx
Fix: Animated List
Pulled from issues: https://github.com/magicuidesign/magicui/issues/333
=> refactor: optimize AnimatedList component

__registry__/index.tsx, config/docs.ts, content/docs/components/ripple-button.mdx, public/r/index.json, public/r/styles/default/ripple-button.json, registry/default/example/ripple-button-demo.tsx, registry/default/magicui/ripple-button.tsx, registry/registry-examples.ts, registry/registry-ui.ts, tailwind.config.cjs
Hello there,
I’ve developed a new button component that includes a ripple animation. I’ve tested it across multiple scenarios and devices to ensure compatibility with the existing features. I have updated the documentation as well.
Please review the changes and let me know your thoughts or if any adjustments are needed.
Thank you!
https://github.com/user-attachments/assets/d105a702-eebd-4e88-9ec4-fb98f3fd2b93
=> feat(button): add new ripple button component

registry/default/magicui/hyper-text.tsx
There should be only one H1 heading on a single page.
=> perf(seo): change motion.h1 to motion.span

registry/default/magicui/avatar-circles.tsx
This commit removes the +0 or null
=> feat: don't show last circle in case numPeople is null or under 0

components/ui/command.tsx
The Command component was not using the correct selector for disabled items. This is due to the new version (1.0) of the cmdk, which uses aria-disabled and data-disabled as booleans instead of undefined.
All items inside command-menu are disabled now. You can check here:
You can check the `cmdk` CHANGELOG [here](https://github.com/pacocoursey/cmdk/releases/tag/v1.0.0)
=> fix(command): adjust class to new cmdk version

registry/default/magicui/hyper-text.tsx
Added some `rootMargin: "-30% 0px -30% 0px"` to trigger the animation when the text comes a little bit close to the middle.
=> fix: gave the hypertext animation to start when in View

registry/default/magicui/morphing-text.tsx
I fixed the `svgFilters` which should resolve the inconsistent animation on Firefox.
=> fix: fixing the morphing text to work on firefox too

content/docs/components/icon-cloud.mdx, package.json, pnpm-lock.yaml
1. #465
-  the icon cloud suddenly stoped rendering color
1. small typo in icon cloud docs
1. bump react-icon-cloud [from 4.1.4 to latest 4.1.6](https://github.com/teaguestockwell/react-icon-cloud/releases)
- @EngenMe [change in 4.1.5 fixed the colors](https://github.com/teaguestockwell/react-icon-cloud/pull/17)
- this change in 4.1.6 [prevent future breaks by locking to a specific version of hosted icon paths & colors](https://github.com/teaguestockwell/react-icon-cloud/commit/b29d8e59346c67708ff30611f62a134b2b2d8ca6)
1. fixed typo
=> fix(icon-cloud): not rendering icon color

__registry__/index.tsx, config/docs.ts, content/docs/components/interactive-grid-pattern.mdx, public/r/index.json, public/r/styles/default/interactive-grid-pattern.json, registry/default/example/interactive-grid-pattern-demo-2.tsx, registry/default/example/interactive-grid-pattern-demo.tsx, registry/default/magicui/interactive-grid-pattern.tsx, registry/registry-examples.ts, registry/registry-ui.ts
This merge request adds a new component to the Background session of MagicUI.
https://github.com/user-attachments/assets/fb156a8f-801b-498a-b2ee-84542481fb1d
=> feat: add Interactive Grid Pattern component

components/mobile-nav.tsx
Adding an `active` state to the mobile navigation menu items and changing the font size to an arbitrary value of 15px instead of the default. I think the default size looks a bit too big, and 15px feels more balanced and justified.
=> fix: mobile sidebar menu active state

CONTRIBUTING.md
Before 
After
Another suggestion is to include the `pnpm format:write` and `pnpm lint:fix` commands in the documentation, so that when everyone is making a PR, it is already formatted and linted correctly.
=> fix: update contribute docs with correct cli example

registry/default/magicui/bento-grid.tsx
This PR simply replaces `ml-2` to `ms-2` and also rotates the arrow 180 degrees on RTL
=> feature(bento): make it RTL compatible

content/docs/components/scratch-to-reveal.mdx
Quite self explanatory, minor bug in the docs.
Missing letter `L` in `onComplete` prop
```
onCompete -> onComplete
```
=> fix: scratch to reveal prop typo

components/mobile-nav.tsx
This PR adds the missing **"Pro"** label to the items in the mobile sidebar, ensuring consistency with the sidebar in the web view.  
Previously, only the web sidebar displayed the **"Pro"** label for paid items, while the mobile sidebar did not.  
- ✅ Added the **"Pro"** label to the mobile sidebar items where applicable.  
- ✅ Ensured styling and visibility match the web sidebar.  
✔️ Improves consistency between mobile and web UI.  
✔️ Prevents user confusion regarding which items are free vs. paid.  
✔️ Verified that **"Pro"** labels appear correctly in both mobile and web sidebars.
=> feat(ui): add Pro label to sidebar items in mobile view

components/mobile-nav.tsx, components/sidebar-nav.tsx
This update enhances the alignment of the sidebar title and labels (`New`, `Pro`) by using `justify-between`.  
Previously, all elements were aligned to the left, which could cause uneven spacing.  
This improvement applies to both web and mobile views, ensuring a more balanced layout.
Let me know if you want any modifications! 😊
=> feat(sidebar): align title and labels with justify-between for better spacing

public/r/globe.json, public/registry.json, registry.json, registry/registry-ui.ts
To resolve the `Module not found: Can't resolve 'motion/react'` error in the globe component in Magic UI: <https://magicui.design/docs/components/globe>
=> Adding motion dependence in the globe component.

registry/magicui/bento-grid.tsx
`translate-y-10` only on desktop for mobile and tablet `cta` is always visible
=> feat: update bento cta visibility

__registry__/index.tsx, config/docs.ts, content/docs/components/comic-text.mdx, public/r/comic-text-demo.json, public/r/comic-text.json, public/registry.json, registry.json, registry/example/comic-text-demo.tsx, registry/magicui/comic-text.tsx, registry/registry-examples.ts, registry/registry-ui.ts
This PR introduces a new `Comic Text` component to our Magic UI library. This component renders text with a fun, comic book-style animation, making it perfect for headlines, callouts, or any place you want to add a bit of pop and character.
**Key Features:**
*   **Comic-Inspired Design**: The component styles text to look like it's straight out of a comic book, featuring a thick black outline, a slight skew, and a halftone-dot background effect.
*   **Smooth Animation**: It uses `framer-motion` to add a subtle spring animation on load, making the text appear with a playful bounce.
*   **Customizable**: You can easily change the font size and pass in custom styles and class names.
**What's Included:**
*   The `ComicText` component.
*   A new documentation page …
=> Add Comic Text component

content/docs/components/smooth-cursor.mdx
Added a new section titled "Hiding Default Browser Cursor" to the SmoothCursor documentation. This section explains how to prevent the native browser cursor from overlapping with the custom cursor using global CSS or Tailwind utility classes. Also includes optional handling for form fields like inputs and textareas to preserve usability.
=> docs: add section for hiding default browser cursor in SmoothCursor docs

registry/magicui/cool-mode.tsx
This PR improves the handling of emoji and text character particles in the `cool-mode` component by implementing proper scaling. Previously, when using emojis as particles, they didn't scale properly with the `size` prop, making them difficult to see at smaller sizes.
- Added specific handling for emoji/text characters (distinguishing them from image URLs)
- Implemented a 3x size multiplier to make emojis more visible
- Added proper CSS positioning with flexbox to center emojis in their container
- Used CSS transform for smooth scaling that maintains emoji quality
```tsx
if (particleType === "circle") {
// Circle SVG code...
particle.appendChild(circleSVG);
} else {
particle.innerHTML = `<img src="${particleType}" width="${size}" height="${size}" style="border-radius: 50%">`;
}
```
```tsx …
```
=> feat: add support for resizing emoji particles
